apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: anvils.test.com
spec:
  group: test.com
  versions:
    - name: v1
      served: true
      storage: false
  scope: Namespaced
  names:
    plural: anvils
    singular: anvil
    kind: Anvil
